# Generated by Django 4.2.2 on 2023-07-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_date_of_birth_alter_teacher_user'),
        ('school_class', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_class', to='teachers.teacher'),
        ),
    ]
