# Generated by Django 4.2.2 on 2023-07-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='for_all_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new',
            name='for_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
