# Generated by Django 4.2.2 on 2023-07-10 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_new_for_all_school_new_for_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL),
        ),
    ]
