# Generated by Django 4.2.2 on 2023-07-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_new_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='for_all_school',
        ),
    ]
