# Generated by Django 4.2.2 on 2023-07-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciences', '0002_alter_science_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
