# Generated by Django 4.2.2 on 2023-07-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_date_of_birth_alter_teacher_user'),
        ('sciences', '0003_alter_science_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='sciences', to='teachers.teacher'),
        ),
    ]
