# Generated by Django 4.2.1 on 2023-06-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='surname',
        ),
    ]
