# Generated by Django 4.2.2 on 2023-07-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='phone_number',
        ),
    ]
