# Generated by Django 4.2.2 on 2023-07-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_class', '0002_initial'),
        ('pupils', '0004_remove_pupil_code_remove_pupil_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupils', to='school_class.schoolclass'),
        ),
    ]
